### PR TITLE
Correct type check for the onBlur handler for SQLEditor

### PR DESCRIPTION
**Pull request by shelldandy**
Otherwise type checking fails when attempting to use the prop as intended:

https://github.com/grafana/grafana-experimental/blob/main/src/sql-editor/components/SQLEditor.tsx#L115-L118

image

### CODE REVIEW

**Comment by gabor** [comment]
hi @shelldandy , could you please explain the user-case where you need this? i mean, `onBlur` already calls `onChange`, so the parent component will be notified about the change (maybe it should not call `onChange`, but that ship has probably sailed already 😄 )

**Comment by shelldandy** [comment]
For some reason on the VariableQueryEditor page the Run Query button on the page sometimes it's not on sync with the rest of the page (probably because on earlier grafana versions that button wasn't there)

So to fix that issue what we've been doing on enterprise Datasources is to add an onBlur event to force a model update of the onChange function so hitting the button works as intended

**Review by gabor — APPROVED** [review]
LGTM 👍

**Review by scottlepp — CHANGES_REQUESTED** [review]
just need to bump the version and changelog

**Review by scottlepp — APPROVED** [review]

**Pull request merged**
