### PR TITLE
Chore: Relax peer dependencies

### PR DESCRIPTION
**Pull request by jackw**
The experimental package is used in Grafana core and on install causes a huge number of post-resolution validation warnings.

image

This PR aims to address these by relaxing the peer dependency semver ranges. I'm pretty confident this package supports these semver range changes as they're used in Grafana core and I'm not aware of any issues there.

### CODE REVIEW

**Review by ivanahuckova — APPROVED** [review]

**Comment by ivanahuckova** [comment]
@jackw do you want me to merge and release?

**Comment by jackw** [comment]
> @jackw do you want me to merge and release?

Yes please, that'd be a big help to me. Thanks @ivanahuckova ! 👍

**Comment by jackw** [comment]
Ah, was I silly and forgot to bump the package.json version @ivanahuckova ? 😞

**Comment by ivanahuckova** [comment]
https://github.com/grafana/grafana-experimental/pull/133

**Pull request merged**
